### ISSUE TITLE
Add "edit jadwal" for created schedule

### ISSUE THREAD

**Issue by fariqodri** [RistekCSUI/susunjadwal#21]

**Comment by firmanhp** [comment]
+1 implement this or i'll delete your fortnite account

**Comment by jonathanfilbert** [comment]
Anyone currently implementing this? If not, I’ll implement it.

**Comment by albadrun** [comment]
yes, feel free to implement it 😃

**Comment by jonathanfilbert** [comment]
I'm thinking besides implementing a feature to edit a jadwal, cloning a jadwal would be an awesome feature to have as well since sometimes we want to make quick modifications to a pre-existing jadwal 🤔 . What do you think @albadrun ? I'm interested in implementing both of them if you're okay and I'm very open to other suggestions 😄

**Comment by jonathanfilbert** [comment]
Currently implementing it here, I'm open for any suggestions or reviews before hitting a PR @albadrun @fairuzi10 
https://github.com/jonathanfilbert/susunjadwal/pull/3

**Comment by jonathanfilbert** [comment]
Done here #55

**Comment by fairuzi10** [comment]
The feature is already merged and ready to use for the next SIAK war, thanks @jonathanfilbert! 😃
